#!/bin/bash
#    QR Code Labels
#    Copyright (C) 2013 Balint Reczey <balint@balintreczey.hu>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

# TODO use temp dir
echo "Generating 3x3 UUID labels on a single page"
LABEL_PDFS=""
for i in $(seq 3); do
    UUID=$(uuid -m)
    ./uuid2qrlabel $UUID
    mkdir $UUID
    LABEL_PDFS="$LABEL_PDFS $UUID-label.pdf $UUID-label.pdf $UUID-label.pdf"
done

pdfnup --no-landscape --nup 3x3 $LABEL_PDFS
rm -rf $LABEL_PDFS

